FROM node:20-alpine3.18

RUN addgroup -S nonroot \
    && adduser -S nonroot -G nonroot
RUN echo "nonroot:pass" | chpasswd
USER nonroot

WORKDIR /app

COPY --chmod=646 . .
RUN npm install --ignore-scripts
# RUN npx prisma generate
CMD ["npm", "run", "start:local"]