FROM node:20 AS builder
WORKDIR /app
COPY . .
RUN npm ci --ignore-scripts
# RUN npx prisma generate
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app ./
CMD ["npm", "run", "start:prod"]
